### ISSUE TITLE
[New feature request] update links

### ISSUE THREAD

**Issue by dugwood** [inetprocess/sugarcrm-apiwrapper#3]
It would be great to add a function to update links of a endpoint. Say we have:
- Contact:
   - endpoint: /Contacts
   - id = abc
 - Addresses:
   - link name: addresses
   - entries:
     - address 1: id = a1
     - address 2: id = a2

I need to post/delete all addresses links of the contact, so run:
`POST against '/Contacts/abc/link/addresses/a1'`
`POST against '/Contacts/abc/link/addresses/a2'`

But may be all links are already okay, so POST is useless, or there's already a link to address 3, so a DELETE must be used too.

Function would be something like (with exceptions thrown on any failed request):
```
SugarClient {
  // $endpoint: 'Contacts'
  // $contact: either a string for the id ('abc'), or the entry: ['id'=>'abc', 'modified_by'=> ...]
  // $link: the name of the link, so 'addresses' in this example
  // $links: ['a1', 'a2']
  public function updateRelatedLinks($endpoint, $entry, $link, $links) {
    1) if $entry is a string => run $this->get('/'.$endpoint.'/'.$entry)
    2) compare $entry->$link against $links with array_diff:
        => query DELETE on each result ($delete++)
    3) compare $links against $entry->$link with array_diff:
        => query POST on each result ($post++)
    4) return something? Perhaps an array with ['added' => $post, 'deleted' => $delete]
  }
}
```

**Comment by remisauvat** [comment]
Thank you for this suggestion. 
We will look into it and see what can we implement.

**Comment by dugwood** [comment]
PR #4 (waiting for the PR to be closed to close this).

**Comment by dugwood** [comment]
Closed as PR was merged into master.
